<br><br>
<center><font size='5'><b>Deep Learning for All_pytorch</b></font><br><br><font size='5'>Chap1. Tensor Manipulation<b></b></font>

# Tensor Manipulation

- 1차원 : 벡터, 1차원 tensor
- 2차원 : Matrix, 2차원 tensor 
- 3차원~~ : Tensor ```이미지 (224,224,3)```
- 4차원 : ```배치+이미지 (64,224,224,3)```
- 5차원 : ```동영상 데이터```

In [1]:
import numpy as np
import torch

## array with numpy

In [5]:
t = np.array([0,1,2,3,4,5,6])
print(t)

[0 1 2 3 4 5 6]


In [6]:
print('Rank or dimension of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank or dimension of t:  1
Shape of t:  (7,)


In [8]:
t = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Rank or dimension of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank or dimension of t:  2
Shape of t:  (3, 3)


## array with PyTorch 

In [2]:
# 0차원 텐서(스칼라)

x = torch.tensor(10)
print(x)
print(x.dim())

tensor(10)
0


In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [18]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [19]:
t = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


## from numpy to tensor

- torch.from_numpy()

In [4]:
t = np.array([0,1,2,3,4,5,6])

tensor = torch.from_numpy(t)
tensor.size()

torch.Size([7])

## Broadcasting

In [20]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [21]:
# vector+scalar
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([1]) # 1 -> [[1,1]]
print(m1+m2)

tensor([[4., 4.]])


## Multiplication vs Matrix multiplication

In [22]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [23]:
m1*m2

tensor([[1., 2.],
        [6., 8.]])

In [24]:
m1.mul(m2)

tensor([[1., 2.],
        [6., 8.]])

## Mean

In [25]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [26]:
# integer에 대해서는 mean()은 안된다

t = torch.LongTensor([1,2])
t.mean()

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [27]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [29]:
print(t.mean())
print(t.mean(dim=0)) # 첫번째 dimension에서 
print(t.mean(dim=1)) # 두번째 디멘젼에서 
print(t.mean(dim=-1))

# 2*2 행렬에서, dim=0이라는 것은 첫번째 dimension을 없애겠다고 생각하면 됨.
# 첫번째 디멘젼을 없애려면 1*2 행렬이 되어야 하므로 
# 반대로 dim=1이면 두번째 디멘젼을 없애겠다고 하는거니까 
# 2*1 행렬이 나와야 함

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [31]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


## Max and Argumax

In [32]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
print(t.max()) # 4개 중에서 가장 큰거 1개만 리턴

tensor(4.)


In [39]:
print(t.max(dim=0)) # 이거는 두개를 리턴함. 맥스값과 argmax 값
# argmax 값은 맥스가 되는 곳의 인덱스값임

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [40]:
print('max : ', t.max(dim=0)[0])
print('max : ', t.max(dim=0)[1])

max :  tensor([3., 4.])
max :  tensor([1, 1])


## View (numpy에서 Reshape)

In [42]:
t = np.array([[[0,1,2],
              [3,4,5]],
              
              [[6,7,8],
              [9,10,11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [43]:
print(ft.view([-1,3])) # 앞에는 모르겠고, 뒤에는 3개의 요소를 가질래 
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [44]:
print(ft.view([-1,1,3])) # 앞에는 모르겠고, 뒤에는 3개의 요소를 가질래 
print(ft.view([-1,1,3]).shape) # 앞에는 모르겠고, 3차원인데 뒤에는 1,3을 가질래 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

- 3x1 2차원에서 뒤에 요소가 1이면 자동으로 없애준다(물기 짠다고 생각하면 됨)

In [47]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [48]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

- 내가 원하는 디멘젼에 1을 넣어줍니다

In [49]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [50]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [51]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [52]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [53]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [54]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [56]:
# ByteTensor는 불리안 값을 저장한다.
# True는 1, False는 0

bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [57]:
print(bt.long())

tensor([1, 0, 0, 1])


In [58]:
print(bt.float())

tensor([1., 0., 0., 1.])


## Concatenate

In [63]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])
print(x); print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [67]:
print(torch.cat([x,y], dim=0)) #dim0이 늘어날 것이다. 4*2사이즈
print(torch.cat([x,y], dim=1)) #dim1이 늘어날 것이다. 2*4사이즈

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [70]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
# 각 크기는 (2,) 벡터

In [71]:
print(torch.stack([x,y,z])) # 새로운 차원이 하나 생겨서 (3,2)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [72]:
print(torch.stack([x,y,z], dim=1)) # (2,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Ones and Zeros

In [74]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)
print(x.shape)

tensor([[0., 1., 2.],
        [2., 1., 0.]])
torch.Size([2, 3])


In [75]:
print(torch.ones_like(x)) # 똑같은 사이즈의 ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [77]:
print(torch.zeros_like(x)) # 똑같은 사이즈의 zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place operation

- 연산하고 결과값이 다시 할당되는 것 

In [79]:
x = torch.FloatTensor([[1,2],[3,4]])

print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [80]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
